sudo: true

matrix:
  include:
    - language: node_js
      node_js:
        - 8
      cache:
        yarn: true
        directories:
          - node_modules
          - app/node_modules

      os:
        - linux
        - osx
      before_install:
        - cd client
      install:
        - yarn
        - cd app && yarn && cd ..

      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start &
        - sleep 3

      script:
        - node --version
        - yarn lint
        # Calling rebuild because for some reason the serialport module is not being
        # compiled properly via electron-rebuild
        # TODO(miguel): Remove npm rebuild when possible
        - cd app && npm rebuild && cd ..
        - yarn run build
        - yarn test
        # We only build in mac os since it supports all the platforms
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn package-all; fi
    - language: go
      go:
        - "1.10.x"
      before_install:
        - cd oauthserver
      script:
        - go version
        - make test
        - make build
