sudo: true

matrix:
  include:
    # Building in MAC OS to be able to generate dmg files.
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js:
        - 8
      env:
        global:
          - ELECTRON_CACHE=$HOME/.cache/electron
          - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      cache:
        yarn: true
        directories:
          - client/node_modules
          - client/app/node_modules
          - $HOME/.cache/electron
          - $HOME/.cache/electron-builder
      before_install:
        - cd client
        - curl -L https://github.com/yarnpkg/yarn/releases/download/v1.6.0/yarn-v1.6.0.tar.gz | tar xvz && mv yarn-v1.6.0 $HOME/.yarn
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn
        - cd app && yarn && cd ..

      script:
        - node --version
        - yarn lint
        # Calling rebuild because for some reason the serialport module is not being
        # compiled properly via electron-rebuild
        # TODO(miguel): Remove npm rebuild when possible
        - cd app && npm rebuild && cd ..
        - yarn run build
        - yarn test
        # We only build in mac os since it supports all the platforms
        - yarn package-all
    - language: go
      go:
        - "1.10.x"
      before_install:
        - cd oauthserver
      script:
        - go version
        - make test
        - make build
