sudo: true

matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js:
        - 8
      cache:
        yarn: true
        directories:
          - node_modules
          - app/node_modules
      before_install:
        - cd client
        - curl -L https://github.com/yarnpkg/yarn/releases/download/v1.6.0/yarn-v1.6.0.tar.gz | tar xvz
        - export PATH="$(pwd)/yarn-v1.6.0/bin:$PATH"
      install:
        - yarn
        - cd app && yarn && cd ..

      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start &
        - sleep 3

      script:
        - node --version
        - yarn lint
        # Calling rebuild because for some reason the serialport module is not being
        # compiled properly via electron-rebuild
        # TODO(miguel): Remove npm rebuild when possible
        - cd app && npm rebuild && cd ..
        - yarn run build
        - yarn test
        # We only build in mac os since it supports all the platforms
        - yarn package-all
    - language: go
      go:
        - "1.10.x"
      before_install:
        - cd oauthserver
      script:
        - go version
        - make test
        - make build
