// flow-typed signature: b85d10862c1ce47b6e748bf46527d270
// flow-typed version: <<STUB>>/jest-plugin-context_v^2.9.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-plugin-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-plugin-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-plugin-context/build/context' {
  declare module.exports: any;
}

declare module 'jest-plugin-context/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-plugin-context/build/context.js' {
  declare module.exports: $Exports<'jest-plugin-context/build/context'>;
}
declare module 'jest-plugin-context/setup.js' {
  declare module.exports: $Exports<'jest-plugin-context/setup'>;
}
