// flow-typed signature: 0a4ebbac6b81750365003188931c27f2
// flow-typed version: <<STUB>>/@slack/client_v^4.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slack/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slack/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slack/client/dist/errors' {
  declare module.exports: any;
}

declare module '@slack/client/dist/IncomingWebhook' {
  declare module.exports: any;
}

declare module '@slack/client/dist/index' {
  declare module.exports: any;
}

declare module '@slack/client/dist/KeepAlive' {
  declare module.exports: any;
}

declare module '@slack/client/dist/logger' {
  declare module.exports: any;
}

declare module '@slack/client/dist/methods' {
  declare module.exports: any;
}

declare module '@slack/client/dist/retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/dist/RTMClient' {
  declare module.exports: any;
}

declare module '@slack/client/dist/util' {
  declare module.exports: any;
}

declare module '@slack/client/dist/WebClient' {
  declare module.exports: any;
}

declare module '@slack/client/examples/basic-incoming-webhook' {
  declare module.exports: any;
}

declare module '@slack/client/examples/basic-rtm-client' {
  declare module.exports: any;
}

declare module '@slack/client/examples/basic-web-client' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/example' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/source/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/source/tests/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/errors' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/IncomingWebhook' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/KeepAlive' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/logger' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/methods' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/RTMClient' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/util' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/dist/WebClient' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/rtm-testing' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/src/IncomingWebhook.spec' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/src/WebClient.spec' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc-to-markdown' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-errors' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-KeepAlive' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-logger' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-methods' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-util' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/async-limiter/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/bench' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/abort' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/async' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/defer' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/iterate' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/readable_asynckit' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/readable_parallel' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/readable_serial_ordered' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/readable_serial' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/state' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/streamify' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/lib/terminator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/parallel' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/serial' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/serialOrdered' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/asynckit/stream' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/cacheable-request/node_modules/lowercase-keys/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/cacheable-request/src/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/clone-response/src/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/combined-stream/lib/combined_stream' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/combined-stream/lib/defer' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/core-util-is/lib/util' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/core-util-is/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/decode-uri-component/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/decompress-response/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/define-properties/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/define-properties/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/delay/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/delayed-stream/lib/delayed_stream' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/duplexer3/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es2015' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es2016' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es2017' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es5' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es6' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/es7' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/assign' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/isFinite' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/isNaN' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/isPrimitive' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/mod' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/helpers/sign' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/operations/2015' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/operations/2016' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/operations/2017' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/operations/es5' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/diffOps' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es2015' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es2016' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es2017' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es5' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es6' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/es7' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/helpers/values' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-abstract/test/tests' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/es5' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/es6' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/helpers/isPrimitive' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/test/es5' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/test/es6' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/es-to-primitive/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/eventemitter3/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/eventemitter3/umd/eventemitter3.min' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/AsyncActionConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/BaseConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/delegateToAncestor' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/GlobalConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/StateConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/StateMachineConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/TimerConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/TransitionConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/configuration/TriggerConfigurator' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/core/HierarchicalStateMachine' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/core/StateMachine' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/core/TaskScheduler' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/Finity' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/utils/invokeEach' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/utils/mapValues' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/lib/utils/merge' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/umd/Finity' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/finity/umd/Finity.min' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/foreach/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/foreach/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/form-data/lib/browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/form-data/lib/form_data' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/form-data/lib/populate' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/from2/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/from2/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/function-bind/implementation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/function-bind/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/function-bind/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/get-stream/buffer-stream' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/get-stream/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/got/errors' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/got/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-symbol-support-x/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x.min' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-symbol-support-x/tests/run' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-to-string-tag-x/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x.min' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has/src/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/has/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/http-cache-semantics/node4/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/inherits/inherits_browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/inherits/inherits' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/into-stream/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-callable/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-callable/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-date-object/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-date-object/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-object/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-object/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-plain-obj/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-regex/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-regex/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-retry-allowed/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-stream/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-symbol/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/is-symbol/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/isarray/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/isarray/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/isurl/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/json-buffer/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/json-buffer/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/keyv/src/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/dist/loglevel' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/dist/loglevel.min' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/Gruntfile' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/lib/loglevel' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/console-fallback-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/cookie-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/default-level-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/get-current-level-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/global-integration-with-new-context' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/global-integration' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/integration-smoke-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/level-setting-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/local-storage-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/method-factory-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/multiple-logger-test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/node-integration' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/test-context-using-apply' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/test-helpers' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/test-qunit' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/loglevel/test/vendor/json2' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/lowercase-keys/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/mime-db/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/mime-types/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/mimic-response/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/normalize-url/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object-assign/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object-keys/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object-keys/isArguments' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object-keys/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/implementation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/polyfill' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/shim' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/test/shimmed' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.entries/test/tests' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/implementation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/polyfill' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/shim' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/shimmed' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/tests' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/implementation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/polyfill' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/shim' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/test/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/test/shimmed' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/object.values/test/tests' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-cancelable/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-defer/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-finally/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-is-promise/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-queue/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-retry/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/p-timeout/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/pify/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/prepend-http/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/process-nextick-args/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/query-string/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/duplex-browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/duplex' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_duplex' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_passthrough' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_readable' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_transform' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_writable' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/BufferList' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/destroy' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream-browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/passthrough' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/readable-browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/readable' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/transform' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/writable-browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/readable-stream/writable' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/responselike/src/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/example/dns' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/example/stop' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/lib/retry_operation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/lib/retry' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/common' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/integration/test-forever' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/integration/test-retry-operation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/integration/test-retry-wrap' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/integration/test-timeouts' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/retry/test/runner' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/safe-buffer/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/safe-buffer/test' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/sort-keys/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/strict-uri-encode/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/string_decoder/lib/string_decoder' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/timed-out/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/url-join/lib/url-join' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/url-join/test/tests' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/url-parse-lax/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/url-to-options/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/util-deprecate/browser' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/util-deprecate/node' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/index' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/buffer-util' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/constants' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/event-target' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/extension' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/permessage-deflate' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/receiver' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/sender' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/validation' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/websocket-server' {
  declare module.exports: any;
}

declare module '@slack/client/examples/node_modules/ws/lib/websocket' {
  declare module.exports: any;
}

declare module '@slack/client/examples/upload-a-file' {
  declare module.exports: any;
}

declare module '@slack/client/rtm-testing' {
  declare module.exports: any;
}

declare module '@slack/client/src/IncomingWebhook.spec' {
  declare module.exports: any;
}

declare module '@slack/client/src/WebClient.spec' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc-to-markdown' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-errors' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-IncomingWebhook' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-KeepAlive' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-logger' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-methods' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client-dist-util' {
  declare module.exports: any;
}

declare module '@slack/client/support/jsdoc/@slack-client' {
  declare module.exports: any;
}

declare module '@slack/client/web-testing' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slack/client/dist/errors.js' {
  declare module.exports: $Exports<'@slack/client/dist/errors'>;
}
declare module '@slack/client/dist/IncomingWebhook.js' {
  declare module.exports: $Exports<'@slack/client/dist/IncomingWebhook'>;
}
declare module '@slack/client/dist/index.js' {
  declare module.exports: $Exports<'@slack/client/dist/index'>;
}
declare module '@slack/client/dist/KeepAlive.js' {
  declare module.exports: $Exports<'@slack/client/dist/KeepAlive'>;
}
declare module '@slack/client/dist/logger.js' {
  declare module.exports: $Exports<'@slack/client/dist/logger'>;
}
declare module '@slack/client/dist/methods.js' {
  declare module.exports: $Exports<'@slack/client/dist/methods'>;
}
declare module '@slack/client/dist/retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/dist/retry-policies'>;
}
declare module '@slack/client/dist/RTMClient.js' {
  declare module.exports: $Exports<'@slack/client/dist/RTMClient'>;
}
declare module '@slack/client/dist/util.js' {
  declare module.exports: $Exports<'@slack/client/dist/util'>;
}
declare module '@slack/client/dist/WebClient.js' {
  declare module.exports: $Exports<'@slack/client/dist/WebClient'>;
}
declare module '@slack/client/examples/basic-incoming-webhook.js' {
  declare module.exports: $Exports<'@slack/client/examples/basic-incoming-webhook'>;
}
declare module '@slack/client/examples/basic-rtm-client.js' {
  declare module.exports: $Exports<'@slack/client/examples/basic-rtm-client'>;
}
declare module '@slack/client/examples/basic-web-client.js' {
  declare module.exports: $Exports<'@slack/client/examples/basic-web-client'>;
}
declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/example.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@sindresorhus/is/dist/example'>;
}
declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@sindresorhus/is/dist/index'>;
}
declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/source/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@sindresorhus/is/dist/source/index'>;
}
declare module '@slack/client/examples/node_modules/@sindresorhus/is/dist/source/tests/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@sindresorhus/is/dist/source/tests/test'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/errors.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/errors'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/IncomingWebhook.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/IncomingWebhook'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/index'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/KeepAlive.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/KeepAlive'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/logger.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/logger'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/methods.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/methods'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/retry-policies'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/RTMClient.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/RTMClient'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/util.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/util'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/dist/WebClient.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/dist/WebClient'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/rtm-testing.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/rtm-testing'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/src/IncomingWebhook.spec.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/src/IncomingWebhook.spec'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/src/WebClient.spec.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/src/WebClient.spec'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc-to-markdown.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc-to-markdown'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-errors.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-errors'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-KeepAlive.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-KeepAlive'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-logger.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-logger'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-methods.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-methods'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-retry-policies'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-util.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client-dist-util'>;
}
declare module '@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/@slack/client/support/jsdoc/@slack-client'>;
}
declare module '@slack/client/examples/node_modules/async-limiter/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/async-limiter/index'>;
}
declare module '@slack/client/examples/node_modules/asynckit/bench.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/bench'>;
}
declare module '@slack/client/examples/node_modules/asynckit/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/index'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/abort.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/abort'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/async.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/async'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/defer.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/defer'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/iterate.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/iterate'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/readable_asynckit.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/readable_asynckit'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/readable_parallel.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/readable_parallel'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/readable_serial_ordered.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/readable_serial_ordered'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/readable_serial.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/readable_serial'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/state.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/state'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/streamify.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/streamify'>;
}
declare module '@slack/client/examples/node_modules/asynckit/lib/terminator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/lib/terminator'>;
}
declare module '@slack/client/examples/node_modules/asynckit/parallel.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/parallel'>;
}
declare module '@slack/client/examples/node_modules/asynckit/serial.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/serial'>;
}
declare module '@slack/client/examples/node_modules/asynckit/serialOrdered.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/serialOrdered'>;
}
declare module '@slack/client/examples/node_modules/asynckit/stream.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/asynckit/stream'>;
}
declare module '@slack/client/examples/node_modules/cacheable-request/node_modules/lowercase-keys/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/cacheable-request/node_modules/lowercase-keys/index'>;
}
declare module '@slack/client/examples/node_modules/cacheable-request/src/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/cacheable-request/src/index'>;
}
declare module '@slack/client/examples/node_modules/clone-response/src/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/clone-response/src/index'>;
}
declare module '@slack/client/examples/node_modules/combined-stream/lib/combined_stream.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/combined-stream/lib/combined_stream'>;
}
declare module '@slack/client/examples/node_modules/combined-stream/lib/defer.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/combined-stream/lib/defer'>;
}
declare module '@slack/client/examples/node_modules/core-util-is/lib/util.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/core-util-is/lib/util'>;
}
declare module '@slack/client/examples/node_modules/core-util-is/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/core-util-is/test'>;
}
declare module '@slack/client/examples/node_modules/decode-uri-component/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/decode-uri-component/index'>;
}
declare module '@slack/client/examples/node_modules/decompress-response/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/decompress-response/index'>;
}
declare module '@slack/client/examples/node_modules/define-properties/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/define-properties/index'>;
}
declare module '@slack/client/examples/node_modules/define-properties/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/define-properties/test/index'>;
}
declare module '@slack/client/examples/node_modules/delay/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/delay/index'>;
}
declare module '@slack/client/examples/node_modules/delayed-stream/lib/delayed_stream.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/delayed-stream/lib/delayed_stream'>;
}
declare module '@slack/client/examples/node_modules/duplexer3/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/duplexer3/index'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es2015.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es2015'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es2016.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es2016'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es2017.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es2017'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es5.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es5'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es6.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es6'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/es7.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/es7'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/assign.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/assign'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/isFinite.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/isFinite'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/isNaN.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/isNaN'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/isPrimitive.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/isPrimitive'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/mod.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/mod'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/helpers/sign.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/helpers/sign'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/index'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/operations/2015.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/operations/2015'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/operations/2016.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/operations/2016'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/operations/2017.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/operations/2017'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/operations/es5.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/operations/es5'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/diffOps.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/diffOps'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es2015.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es2015'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es2016.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es2016'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es2017.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es2017'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es5.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es5'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es6.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es6'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/es7.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/es7'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/helpers/values.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/helpers/values'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/index'>;
}
declare module '@slack/client/examples/node_modules/es-abstract/test/tests.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-abstract/test/tests'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/es5.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/es5'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/es6.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/es6'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/helpers/isPrimitive.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/helpers/isPrimitive'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/index'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/test/es5.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/test/es5'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/test/es6.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/test/es6'>;
}
declare module '@slack/client/examples/node_modules/es-to-primitive/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/es-to-primitive/test/index'>;
}
declare module '@slack/client/examples/node_modules/eventemitter3/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/eventemitter3/index'>;
}
declare module '@slack/client/examples/node_modules/eventemitter3/umd/eventemitter3.min.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/eventemitter3/umd/eventemitter3.min'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/AsyncActionConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/AsyncActionConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/BaseConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/BaseConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/delegateToAncestor.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/delegateToAncestor'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/GlobalConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/GlobalConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/index'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/StateConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/StateConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/StateMachineConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/StateMachineConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/TimerConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/TimerConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/TransitionConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/TransitionConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/configuration/TriggerConfigurator.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/configuration/TriggerConfigurator'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/core/HierarchicalStateMachine.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/core/HierarchicalStateMachine'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/core/StateMachine.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/core/StateMachine'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/core/TaskScheduler.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/core/TaskScheduler'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/Finity.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/Finity'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/index'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/utils/invokeEach.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/utils/invokeEach'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/utils/mapValues.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/utils/mapValues'>;
}
declare module '@slack/client/examples/node_modules/finity/lib/utils/merge.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/lib/utils/merge'>;
}
declare module '@slack/client/examples/node_modules/finity/umd/Finity.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/umd/Finity'>;
}
declare module '@slack/client/examples/node_modules/finity/umd/Finity.min.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/finity/umd/Finity.min'>;
}
declare module '@slack/client/examples/node_modules/foreach/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/foreach/index'>;
}
declare module '@slack/client/examples/node_modules/foreach/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/foreach/test'>;
}
declare module '@slack/client/examples/node_modules/form-data/lib/browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/form-data/lib/browser'>;
}
declare module '@slack/client/examples/node_modules/form-data/lib/form_data.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/form-data/lib/form_data'>;
}
declare module '@slack/client/examples/node_modules/form-data/lib/populate.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/form-data/lib/populate'>;
}
declare module '@slack/client/examples/node_modules/from2/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/from2/index'>;
}
declare module '@slack/client/examples/node_modules/from2/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/from2/test'>;
}
declare module '@slack/client/examples/node_modules/function-bind/implementation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/function-bind/implementation'>;
}
declare module '@slack/client/examples/node_modules/function-bind/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/function-bind/index'>;
}
declare module '@slack/client/examples/node_modules/function-bind/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/function-bind/test/index'>;
}
declare module '@slack/client/examples/node_modules/get-stream/buffer-stream.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/get-stream/buffer-stream'>;
}
declare module '@slack/client/examples/node_modules/get-stream/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/get-stream/index'>;
}
declare module '@slack/client/examples/node_modules/got/errors.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/got/errors'>;
}
declare module '@slack/client/examples/node_modules/got/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/got/index'>;
}
declare module '@slack/client/examples/node_modules/has-symbol-support-x/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-symbol-support-x/index'>;
}
declare module '@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x'>;
}
declare module '@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x.min.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-symbol-support-x/lib/has-symbol-support-x.min'>;
}
declare module '@slack/client/examples/node_modules/has-symbol-support-x/tests/run.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-symbol-support-x/tests/run'>;
}
declare module '@slack/client/examples/node_modules/has-to-string-tag-x/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-to-string-tag-x/index'>;
}
declare module '@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x'>;
}
declare module '@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x.min.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has-to-string-tag-x/lib/has-to-string-tag-x.min'>;
}
declare module '@slack/client/examples/node_modules/has/src/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has/src/index'>;
}
declare module '@slack/client/examples/node_modules/has/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/has/test/index'>;
}
declare module '@slack/client/examples/node_modules/http-cache-semantics/node4/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/http-cache-semantics/node4/index'>;
}
declare module '@slack/client/examples/node_modules/inherits/inherits_browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/inherits/inherits_browser'>;
}
declare module '@slack/client/examples/node_modules/inherits/inherits.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/inherits/inherits'>;
}
declare module '@slack/client/examples/node_modules/into-stream/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/into-stream/index'>;
}
declare module '@slack/client/examples/node_modules/is-callable/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-callable/index'>;
}
declare module '@slack/client/examples/node_modules/is-callable/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-callable/test'>;
}
declare module '@slack/client/examples/node_modules/is-date-object/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-date-object/index'>;
}
declare module '@slack/client/examples/node_modules/is-date-object/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-date-object/test'>;
}
declare module '@slack/client/examples/node_modules/is-object/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-object/index'>;
}
declare module '@slack/client/examples/node_modules/is-object/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-object/test/index'>;
}
declare module '@slack/client/examples/node_modules/is-plain-obj/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-plain-obj/index'>;
}
declare module '@slack/client/examples/node_modules/is-regex/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-regex/index'>;
}
declare module '@slack/client/examples/node_modules/is-regex/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-regex/test'>;
}
declare module '@slack/client/examples/node_modules/is-retry-allowed/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-retry-allowed/index'>;
}
declare module '@slack/client/examples/node_modules/is-stream/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-stream/index'>;
}
declare module '@slack/client/examples/node_modules/is-symbol/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-symbol/index'>;
}
declare module '@slack/client/examples/node_modules/is-symbol/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/is-symbol/test/index'>;
}
declare module '@slack/client/examples/node_modules/isarray/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/isarray/index'>;
}
declare module '@slack/client/examples/node_modules/isarray/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/isarray/test'>;
}
declare module '@slack/client/examples/node_modules/isurl/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/isurl/index'>;
}
declare module '@slack/client/examples/node_modules/json-buffer/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/json-buffer/index'>;
}
declare module '@slack/client/examples/node_modules/json-buffer/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/json-buffer/test/index'>;
}
declare module '@slack/client/examples/node_modules/keyv/src/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/keyv/src/index'>;
}
declare module '@slack/client/examples/node_modules/loglevel/dist/loglevel.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/dist/loglevel'>;
}
declare module '@slack/client/examples/node_modules/loglevel/dist/loglevel.min.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/dist/loglevel.min'>;
}
declare module '@slack/client/examples/node_modules/loglevel/Gruntfile.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/Gruntfile'>;
}
declare module '@slack/client/examples/node_modules/loglevel/lib/loglevel.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/lib/loglevel'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/console-fallback-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/console-fallback-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/cookie-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/cookie-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/default-level-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/default-level-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/get-current-level-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/get-current-level-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/global-integration-with-new-context.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/global-integration-with-new-context'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/global-integration.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/global-integration'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/integration-smoke-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/integration-smoke-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/level-setting-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/level-setting-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/local-storage-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/local-storage-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/method-factory-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/method-factory-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/multiple-logger-test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/multiple-logger-test'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/node-integration.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/node-integration'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/test-context-using-apply.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/test-context-using-apply'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/test-helpers.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/test-helpers'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/test-qunit.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/test-qunit'>;
}
declare module '@slack/client/examples/node_modules/loglevel/test/vendor/json2.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/loglevel/test/vendor/json2'>;
}
declare module '@slack/client/examples/node_modules/lowercase-keys/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/lowercase-keys/index'>;
}
declare module '@slack/client/examples/node_modules/mime-db/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/mime-db/index'>;
}
declare module '@slack/client/examples/node_modules/mime-types/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/mime-types/index'>;
}
declare module '@slack/client/examples/node_modules/mimic-response/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/mimic-response/index'>;
}
declare module '@slack/client/examples/node_modules/normalize-url/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/normalize-url/index'>;
}
declare module '@slack/client/examples/node_modules/object-assign/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object-assign/index'>;
}
declare module '@slack/client/examples/node_modules/object-keys/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object-keys/index'>;
}
declare module '@slack/client/examples/node_modules/object-keys/isArguments.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object-keys/isArguments'>;
}
declare module '@slack/client/examples/node_modules/object-keys/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object-keys/test/index'>;
}
declare module '@slack/client/examples/node_modules/object.entries/implementation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/implementation'>;
}
declare module '@slack/client/examples/node_modules/object.entries/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/index'>;
}
declare module '@slack/client/examples/node_modules/object.entries/polyfill.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/polyfill'>;
}
declare module '@slack/client/examples/node_modules/object.entries/shim.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/shim'>;
}
declare module '@slack/client/examples/node_modules/object.entries/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/test/index'>;
}
declare module '@slack/client/examples/node_modules/object.entries/test/shimmed.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/test/shimmed'>;
}
declare module '@slack/client/examples/node_modules/object.entries/test/tests.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.entries/test/tests'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/implementation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/implementation'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/index'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/polyfill.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/polyfill'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/shim.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/shim'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/test/index'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/shimmed.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/test/shimmed'>;
}
declare module '@slack/client/examples/node_modules/object.getownpropertydescriptors/test/tests.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.getownpropertydescriptors/test/tests'>;
}
declare module '@slack/client/examples/node_modules/object.values/implementation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/implementation'>;
}
declare module '@slack/client/examples/node_modules/object.values/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/index'>;
}
declare module '@slack/client/examples/node_modules/object.values/polyfill.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/polyfill'>;
}
declare module '@slack/client/examples/node_modules/object.values/shim.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/shim'>;
}
declare module '@slack/client/examples/node_modules/object.values/test/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/test/index'>;
}
declare module '@slack/client/examples/node_modules/object.values/test/shimmed.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/test/shimmed'>;
}
declare module '@slack/client/examples/node_modules/object.values/test/tests.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/object.values/test/tests'>;
}
declare module '@slack/client/examples/node_modules/p-cancelable/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-cancelable/index'>;
}
declare module '@slack/client/examples/node_modules/p-defer/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-defer/index'>;
}
declare module '@slack/client/examples/node_modules/p-finally/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-finally/index'>;
}
declare module '@slack/client/examples/node_modules/p-is-promise/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-is-promise/index'>;
}
declare module '@slack/client/examples/node_modules/p-queue/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-queue/index'>;
}
declare module '@slack/client/examples/node_modules/p-retry/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-retry/index'>;
}
declare module '@slack/client/examples/node_modules/p-timeout/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/p-timeout/index'>;
}
declare module '@slack/client/examples/node_modules/pify/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/pify/index'>;
}
declare module '@slack/client/examples/node_modules/prepend-http/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/prepend-http/index'>;
}
declare module '@slack/client/examples/node_modules/process-nextick-args/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/process-nextick-args/index'>;
}
declare module '@slack/client/examples/node_modules/query-string/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/query-string/index'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/duplex-browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/duplex-browser'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/duplex.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/duplex'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_duplex.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/_stream_duplex'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_passthrough.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/_stream_passthrough'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_readable.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/_stream_readable'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_transform.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/_stream_transform'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/_stream_writable.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/_stream_writable'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/BufferList.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/internal/streams/BufferList'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/destroy.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/internal/streams/destroy'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream-browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream-browser'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/lib/internal/streams/stream'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/passthrough.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/passthrough'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/readable-browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/readable-browser'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/readable.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/readable'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/transform.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/transform'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/writable-browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/writable-browser'>;
}
declare module '@slack/client/examples/node_modules/readable-stream/writable.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/readable-stream/writable'>;
}
declare module '@slack/client/examples/node_modules/responselike/src/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/responselike/src/index'>;
}
declare module '@slack/client/examples/node_modules/retry/example/dns.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/example/dns'>;
}
declare module '@slack/client/examples/node_modules/retry/example/stop.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/example/stop'>;
}
declare module '@slack/client/examples/node_modules/retry/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/index'>;
}
declare module '@slack/client/examples/node_modules/retry/lib/retry_operation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/lib/retry_operation'>;
}
declare module '@slack/client/examples/node_modules/retry/lib/retry.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/lib/retry'>;
}
declare module '@slack/client/examples/node_modules/retry/test/common.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/common'>;
}
declare module '@slack/client/examples/node_modules/retry/test/integration/test-forever.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/integration/test-forever'>;
}
declare module '@slack/client/examples/node_modules/retry/test/integration/test-retry-operation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/integration/test-retry-operation'>;
}
declare module '@slack/client/examples/node_modules/retry/test/integration/test-retry-wrap.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/integration/test-retry-wrap'>;
}
declare module '@slack/client/examples/node_modules/retry/test/integration/test-timeouts.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/integration/test-timeouts'>;
}
declare module '@slack/client/examples/node_modules/retry/test/runner.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/retry/test/runner'>;
}
declare module '@slack/client/examples/node_modules/safe-buffer/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/safe-buffer/index'>;
}
declare module '@slack/client/examples/node_modules/safe-buffer/test.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/safe-buffer/test'>;
}
declare module '@slack/client/examples/node_modules/sort-keys/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/sort-keys/index'>;
}
declare module '@slack/client/examples/node_modules/strict-uri-encode/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/strict-uri-encode/index'>;
}
declare module '@slack/client/examples/node_modules/string_decoder/lib/string_decoder.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/string_decoder/lib/string_decoder'>;
}
declare module '@slack/client/examples/node_modules/timed-out/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/timed-out/index'>;
}
declare module '@slack/client/examples/node_modules/url-join/lib/url-join.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/url-join/lib/url-join'>;
}
declare module '@slack/client/examples/node_modules/url-join/test/tests.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/url-join/test/tests'>;
}
declare module '@slack/client/examples/node_modules/url-parse-lax/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/url-parse-lax/index'>;
}
declare module '@slack/client/examples/node_modules/url-to-options/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/url-to-options/index'>;
}
declare module '@slack/client/examples/node_modules/util-deprecate/browser.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/util-deprecate/browser'>;
}
declare module '@slack/client/examples/node_modules/util-deprecate/node.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/util-deprecate/node'>;
}
declare module '@slack/client/examples/node_modules/ws/index.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/index'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/buffer-util.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/buffer-util'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/constants.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/constants'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/event-target.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/event-target'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/extension.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/extension'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/permessage-deflate.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/permessage-deflate'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/receiver.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/receiver'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/sender.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/sender'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/validation.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/validation'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/websocket-server.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/websocket-server'>;
}
declare module '@slack/client/examples/node_modules/ws/lib/websocket.js' {
  declare module.exports: $Exports<'@slack/client/examples/node_modules/ws/lib/websocket'>;
}
declare module '@slack/client/examples/upload-a-file.js' {
  declare module.exports: $Exports<'@slack/client/examples/upload-a-file'>;
}
declare module '@slack/client/rtm-testing.js' {
  declare module.exports: $Exports<'@slack/client/rtm-testing'>;
}
declare module '@slack/client/src/IncomingWebhook.spec.js' {
  declare module.exports: $Exports<'@slack/client/src/IncomingWebhook.spec'>;
}
declare module '@slack/client/src/WebClient.spec.js' {
  declare module.exports: $Exports<'@slack/client/src/WebClient.spec'>;
}
declare module '@slack/client/support/jsdoc-to-markdown.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc-to-markdown'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-errors.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-errors'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-IncomingWebhook.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-IncomingWebhook'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-KeepAlive.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-KeepAlive'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-logger.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-logger'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-methods.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-methods'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-retry-policies'>;
}
declare module '@slack/client/support/jsdoc/@slack-client-dist-util.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client-dist-util'>;
}
declare module '@slack/client/support/jsdoc/@slack-client.js' {
  declare module.exports: $Exports<'@slack/client/support/jsdoc/@slack-client'>;
}
declare module '@slack/client/web-testing.js' {
  declare module.exports: $Exports<'@slack/client/web-testing'>;
}
